
import java.awt.event.KeyEvent;// this is so that i can use a line of code that lets the user use the enter key instead of the button 
import java.awt.event.*;//This is part of the import that lets me close the page and go to the next one using the Close method
import java.awt.*;//This is part of the import that lets me close the page and go to the next one using the Close method

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Blake Hadaway
 * January 25th, this is the title page that the user selects what section to go to through a text box
 */
public class TitlePage extends javax.swing.JFrame {

     /**
     * Creates new form TitlePage
     */
    public TitlePage() {
        initComponents();
    }

    public void closePage() {// this is the method i use to close the page 
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);// this is the line of code that will close the page 
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);// this is accessing the tool kit to be able to close the page
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        maunalButton = new javax.swing.JButton();
        outputTextField = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Swish City Trivia");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rule Violations: 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Foul Shot Rules: 2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NBA Knowledge: 3  ");

        inputText.setBackground(new java.awt.Color(0, 0, 0));
        inputText.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        inputText.setForeground(new java.awt.Color(255, 255, 255));
        inputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextKeyPressed(evt);
            }
        });

        enterButton.setBackground(new java.awt.Color(0, 0, 0));
        enterButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterButton.setForeground(new java.awt.Color(255, 255, 255));
        enterButton.setText("Enter");
        enterButton.setToolTipText("");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        maunalButton.setBackground(new java.awt.Color(0, 0, 0));
        maunalButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maunalButton.setForeground(new java.awt.Color(255, 255, 255));
        maunalButton.setText("Maunal");
        maunalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maunalButtonActionPerformed(evt);
            }
        });

        outputTextField.setEditable(false);
        outputTextField.setBackground(new java.awt.Color(0, 0, 0));
        outputTextField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        outputTextField.setForeground(new java.awt.Color(255, 255, 255));
        outputTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel2)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(maunalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(maunalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        try { // so Mrs. Marsh doesn't kill my program
            int type; // making an int variable named type for what section to go to 
            type = Integer.parseInt(inputText.getText()); // setting type to what the user inputs 
            if (type == 1) {// if the user inputs 1, this will excute
                closePage();// this is calling the close method
                ruleQuestons s = new ruleQuestons();// this is opening the rule violations section
                s.setVisible(true);// this is setting the visiblity of the page to be true so that the user can see the page
            } else if (type == 2) {// if the user inputs 2, this will excute
                closePage();// calling close method
                foulRules s = new foulRules();// this is opening the foul rules section
                s.setVisible(true);// this is setting the the page to be visable 
            } else if (type == 3) {// if the user inputs 3, this will excute
                closePage();// calling the close page method
                nbaKnow s = new nbaKnow();// this is opening the NBA Knowledge section
                s.setVisible(true);// setting so that the page is visable to the user
            } else {// if all other statments aren't true, this will excute
                outputTextField.setText("Please enter one of the numbers above for that set of questions");//setting the output label
            }
        } catch (Exception e) {// Catching bad user input
            outputTextField.setText("Please enter a input of 1-3 to choose your section");// outputs this if the user inputs bad user input aswell
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void maunalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maunalButtonActionPerformed
        closePage(); //calling the close method
        manual s = new manual();// opening the manual page
        s.setVisible(true);// setting the next page to be visble for the user
    }//GEN-LAST:event_maunalButtonActionPerformed

    private void inputTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextKeyPressed
        
         try { // so Mrs. Marsh doesn't kill my program
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) { // this is for if the user presses enter instead of using the button
             int type; // making an int variable named type for what section to go to 
            type = Integer.parseInt(inputText.getText()); // setting type to what the user inputs 
            if (type == 1) {// if the user inputs 1, this will excute
                closePage();// this is calling the close method
                ruleQuestons s = new ruleQuestons();// this is opening the rule violations section
                s.setVisible(true);// this is setting the visiblity of the page to be true so that the user can see the page
            } else if (type == 2) {// if the user inputs 2, this will excute
                closePage();// calling close method
                foulRules s = new foulRules();// this is opening the foul rules section
                s.setVisible(true);// this is setting the the page to be visable 
            } else if (type == 3) {// if the user inputs 3, this will excute
                closePage();// calling the close page method
                nbaKnow s = new nbaKnow();// this is opening the NBA Knowledge section
                s.setVisible(true);// setting so that the page is visable to the user
            } else {// if all other statments aren't true, this will excute
                outputTextField.setText("Please enter one of the numbers above for that set of questions");//setting the output label
            }
            }
         }catch (Exception e) {// Catching bad user input
            outputTextField.setText("Please enter a input of 1-3 to choose your section");// outputs this if the user inputs bad user input aswell
         }
       
    }//GEN-LAST:event_inputTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitlePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField inputText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maunalButton;
    private javax.swing.JTextField outputTextField;
    // End of variables declaration//GEN-END:variables
}
